version: '3.8'

services:
  ai-debugger:
    build: .
    ports:
      - "8501:8501"  # Streamlit
      - "8000:8000"  # FastAPI
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: streamlit run app/streamlit_app.py --server.port=8501 --server.address=0.0.0.0

  api-only:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - .:/app
    command: uvicorn app.fastapi_app:app --host 0.0.0.0 --port 8000